apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  HOST: "{{ .Release.Name }}-mysql"
  database_port: "{{ .Values.mysql.primary.services.port }}"
  DB: "{{ .Values.mysql.auth.database }}"
