apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret
spec:
  secretStoreRef:
    name: example-secret-store
    kind: SecretStore
  target:
    name: {{ .Chart.Name }}-secret
    creationPolicy: Owner
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: PASSWORD
    - secretKey: USER
      remoteRef:
        key: USER
