apiVersion: v1
kind: Secret
metadata:
  name: azure-secret-sp
type: Opaque
data:
  ClientID: YzVhMzA1ODQtNzg1Ni00OWRlLWEyOGQtZWU2N2Y5MDJkNzE0  
  ClientSecret: MVRaOFF+WU9Xd3o0dlZ1OTZibH5qejJMNkVQM3pTei5kX0p3fmJ1Mw==
